const state={sources:[],articles:[],selected:[],selectedTags:new Set(),customTags:new Set(),editorial:null,readerPage:0,shuffled:false};
const titles={dashboard:"Dashboard",sources:"My Sources",articles:"This Week",magazine:"Magazine",reader:"Reader",archive:"Archive"};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const cfg=window.WEEKLY_CONFIG||{};
const hasSupabase=()=>Boolean(cfg.supabaseUrl&&(cfg.supabaseAnonKey||cfg.supabasePublishableKey)&&!cfg.supabaseUrl.includes("YOUR_PROJECT_REF"));
const supabaseKey=()=>cfg.supabaseAnonKey||cfg.supabasePublishableKey||"";
const apiBase=()=>cfg.supabaseUrl.replace(/\/$/,"")+"/rest/v1";
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));$("#screen-title").textContent=titles[id]||"Dashboard"}
function setConnection(text,ok=false){const el=$("#connection-status");if(!el)return;el.textContent=text;el.classList.toggle("ok",ok)}
async function db(path,options={}){const key=supabaseKey();const headers={apikey:key,Authorization:`Bearer ${key}`,...(options.headers||{})};const r=await fetch(apiBase()+path,{...options,headers});if(!r.ok){let msg=await r.text();throw new Error(`${r.status} ${msg}`)}if(r.status===204)return null;return r.json()}
async function loadSources(){if(!hasSupabase())throw new Error("Supabase no está configurado. Crea config.js.");return db("/sources?select=id,name,url,category,enabled,created_at&order=created_at.asc")}
async function addSource(){if(!hasSupabase()){alert("Primero configura Supabase en config.js. Mira README.md.");return}const name=prompt("Nombre del medio:","");if(name===null)return;const url=prompt("URL del RSS / Atom:","");if(url===null)return;const category=prompt("Categoría (Technology, Games, Culture, World, Other):","Technology");if(category===null)return;if(!name.trim()||!url.trim()){alert("El nombre y la URL son obligatorios.");return}try{await db("/sources",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({name:name.trim(),url:url.trim(),category:category.trim()||"Other",enabled:true})});await refreshSources();show("sources");alert("Feed añadido correctamente. 🎉")}catch(err){console.error(err);alert("No pude guardar el feed.\n\n"+err.message)}}
async function removeSource(id,name){if(!confirm(`¿Eliminar "${name}" de WEEKLY?`))return;try{await db(`/sources?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});await refreshSources()}catch(err){console.error(err);alert("No pude eliminar el feed.\n\n"+err.message)}}
function renderSources(){const box=$("#source-grid");box.innerHTML="";state.sources.forEach(s=>{const e=document.createElement("div");e.className="source";e.innerHTML='<span class="dot"></span><div class="source-copy"><strong></strong><small></small><em></em></div><button class="remove">REMOVE</button>';e.querySelector("strong").textContent=s.name;e.querySelector("small").textContent=`${s.category||"Other"} · RSS`;e.querySelector("em").textContent=s.url;e.querySelector(".remove").onclick=()=>removeSource(s.id,s.name);box.appendChild(e)});$("#source-count").textContent=`${state.sources.filter(s=>s.enabled!==false).length} ACTIVE FEEDS`}
async function refreshSources(){if(!hasSupabase()){setConnection("SUPABASE NOT CONFIGURED");renderSources();return}try{state.sources=await loadSources();setConnection("SUPABASE CONNECTED",true);renderSources();updateDash()}catch(err){console.error(err);setConnection("SUPABASE ERROR");alert("No pude leer Supabase.\n\n"+err.message)}}
const TAG_STOP=new Set("the a an and or of to in on for with from by is are was were this that how why what your you new news more into about after as at it its there their they has have had will would could should just than then very been being not you our their from about today week best one two three get gets can may might while over under who where when into onto only also says said according latest plus here this these those all any any more most some such other another much many much new own its his her them he she we us i me my mine de an der die das und für mit von ist sind auf den im die der ein eine the los las del para por con que una uno como sus más este esta estos estas puede pueden fue han ha hay ya hoy según sobre entre tras al se su es en de".split());
function deriveTags(a){const text=`${a.title||""} ${a.description||""} ${(a.headings?.h1||[]).join(" ")} ${(a.headings?.h2||[]).join(" ")}`.toLowerCase();const words=(text.match(/[a-zA-ZÀ-ÿ0-9]{4,}/g)||[]).map(w=>w.toLowerCase()).filter(w=>!TAG_STOP.has(w));const freq={};words.forEach(w=>freq[w]=(freq[w]||0)+1);const generic=new Set(["history","story","article","selected","source","week","today","best","world","thing","things","edition","review","technology","games"]);const keywords=Object.entries(freq).filter(([w])=>!generic.has(w)).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,5).map(([w])=>w.toUpperCase());const base=[];if(a.category)base.push(String(a.category).toUpperCase());if(Array.isArray(a.tags))base.push(...a.tags.map(x=>String(x).toUpperCase()));return [...new Set([...base,...keywords])].slice(0,8)}
const CUSTOM_ALIASES={
  "ANIME":["anime","manga","otaku","japanese animation","shonen","isekai","studio ghibli"],
  "MARVEL":["marvel","mcu","avengers","spider-man","spiderman","x-men","xmen","deadpool","fantastic four","guardians of the galaxy"],
  "DC":["dc comics","dc","batman","superman","wonder woman","justice league","joker","gotham"],
  "RETRO GAMING":["retro gaming","retro game","classic games","arcade","nes","snes","game boy","gameboy","mega drive","genesis","dreamcast","playstation 1","ps1","playstation 2","ps2","n64","sega saturn"],
  "POKEMON":["pokemon","pokémon","pikachu","game freak"],
  "MANGA":["manga","shonen","shojo","seinen","josei"],
  "STAR WARS":["star wars","lightsaber","jedi","sith","mandalorian","skywalker"],
  "HORROR":["horror","horr","slasher","survival horror","creepy","ghost","vampire","zombie"]
};
function allTags(){const m=new Map();state.articles.forEach(a=>{(a.tags?.length?a.tags:deriveTags(a)).forEach(t=>m.set(t,(m.get(t)||0)+1))});return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function articleSearchText(a){return `${a.title||""} ${a.description||""} ${a.source||""} ${(a.category||"")} ${(a.headings?.h1||[]).join(" ")} ${(a.headings?.h2||[]).join(" ")} ${(a.tags||[]).join(" ")}`.toLowerCase()}
function topicAliases(topic){const key=String(topic||"").trim().toUpperCase();return [key.toLowerCase(),...(CUSTOM_ALIASES[key]||[])].filter(Boolean)}
function matchesCustomTopic(a,topic){const text=articleSearchText(a);return topicAliases(topic).some(alias=>{const q=alias.toLowerCase().trim();return q.length>=2&&text.includes(q)})}
function matchesTags(a){if(!state.selectedTags.size&&!state.customTags.size)return true;const tags=a.tags?.length?a.tags:deriveTags(a);const auto=tags.some(t=>state.selectedTags.has(String(t).toUpperCase()));const custom=[...state.customTags].some(t=>matchesCustomTopic(a,t));return auto||custom}
function candidatePool(){return state.articles.filter(matchesTags)}
function shuffleArray(arr){const out=[...arr];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function chooseRandomStories(pool=candidatePool()){const ranked=shuffleArray(pool.slice()).sort((a,b)=>((b.editorialScore||0)-(a.editorialScore||0))*(Math.random()*.55+.45));const out=[],counts={};for(const a of ranked){const cat=a.category||"Other";if((counts[cat]||0)>=8)continue;out.push(a);counts[cat]=(counts[cat]||0)+1;if(out.length>=24)break}return out}
function sync(){if(!state.selected.length||state.shuffled){state.selected=chooseRandomStories();state.shuffled=false}if(!state.selected.length)state.selected=state.articles.filter(a=>a.selected).slice(0,24);updateCounts()}
function saveTopics(){localStorage.setItem("weekly.selectedTags",JSON.stringify([...state.selectedTags]));localStorage.setItem("weekly.customTags",JSON.stringify([...state.customTags]))}
function rerenderTopicSelection(){state.selected=[];state.shuffled=true;saveTopics();renderTags();renderArticles();renderMagazine()}
function addCustomTopic(raw){const topic=String(raw||"").trim().replace(/\s+/g," ");if(!topic)return false;const key=topic.toUpperCase();if(state.customTags.has(key)||state.selectedTags.has(key))return false;state.customTags.add(key);rerenderTopicSelection();return true}
function removeCustomTopic(topic){state.customTags.delete(String(topic).toUpperCase());rerenderTopicSelection()}
function renderTags(){const box=$("#tag-cloud");if(!box)return;box.innerHTML="";const custom=[...state.customTags];if(custom.length){const head=document.createElement("div");head.className="custom-topic-list";head.innerHTML=custom.map(t=>`<button class="tag-chip custom-chip active" data-custom-topic="${esc(t)}"><span>${esc(t)}</span><small>×</small></button>`).join("");box.appendChild(head);head.querySelectorAll("[data-custom-topic]").forEach(b=>b.onclick=()=>removeCustomTopic(b.dataset.customTopic))}
const tags=allTags();const cloud=document.createElement("div");cloud.className="auto-tag-list";tags.forEach(([tag,count])=>{const b=document.createElement("button");b.className="tag-chip"+(state.selectedTags.has(tag)?" active":"");b.innerHTML=`<span>${esc(tag)}</span><small>${count}</small>`;b.onclick=()=>{if(state.selectedTags.has(tag))state.selectedTags.delete(tag);else state.selectedTags.add(tag);rerenderTopicSelection()};cloud.appendChild(b)});box.appendChild(cloud);$("#tag-count").textContent=`${state.selectedTags.size+state.customTags.size} SELECTED`}
function renderArticles(){const box=$("#article-list");if(!box)return;const pool=candidatePool();if(!state.selected.length||state.shuffled){state.selected=chooseRandomStories(pool);state.shuffled=false}$("#pool-stat").textContent=`${pool.length} STORIES IN POOL`;const activeTopics=[...state.selectedTags,...state.customTags];$("#pool-note").textContent=activeTopics.length?`Temas: ${activeTopics.join(" · ")}`:"Todo el feed está disponible. WEEKLY elegirá una combinación al azar.";box.innerHTML="";shuffleArray(pool).slice(0,12).forEach(a=>{const l=document.createElement("div");l.className="article preview-article";const tags=(a.tags?.length?a.tags:deriveTags(a)).slice(0,4);l.innerHTML=`<div class="article-thumb">${a.image?`<img src="${esc(a.image)}" alt="">`:""}</div><div><span class="cat">${esc((a.category||"OTHER").toUpperCase())}</span><h3>${esc(a.title)}</h3><p>${esc(a.source)} · ${esc((a.published||"").slice(0,10))}</p><div class="mini-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div></div><span class="score">${a.editorialScore||"-"}</span>`;box.appendChild(l)});updateCounts()}
function updateCounts(){const pool=candidatePool();$("#article-count").textContent=`${state.selected.length} SELECTED · ${pool.length} IN POOL`;$("#selected-stat").textContent=`${state.selected.length} SELECTED`}
function storyFor(a){return(state.editorial?.stories||[]).find(s=>s.article_id===state.articles.indexOf(a))||null}
function articleTags(a){return(a?.tags?.length?a.tags:deriveTags(a)).slice(0,5)}
function coverImage(a,cls="cover-image",label="WEEKLY FEATURE"){return a?.image?`<div class="${cls}"><img src="${esc(a.image)}" alt=""><span>${esc(label)}</span></div>`:`<div class="${cls}"><span>${esc(label)}</span></div>`}
function storyTitle(a){const st=storyFor(a);return st?.headline||a?.title||"UNTITLED STORY"}
function renderMagazine(){sync();const s=state.selected;const cover=s[0];$("#cover-dek").textContent=`${s.length} stories · ${state.sources.length} sources · ${state.editorial?.status==="ai"?"AI EDITOR":"RSS EDITOR"}`;$("#mag-cover-title").textContent=storyTitle(cover)||"THE NEWS DESERVES A BETTER INTERFACE.";$("#issue-number").textContent="036";const activeTopics=[...state.selectedTags,...state.customTags];$("#cover-tags").textContent=activeTopics.length?activeTopics.join(" · "):"TAG MIX · RANDOMIZED";$("#cover-count").textContent=`${s.length} STORIES`;const box=$("#cover-stories");box.innerHTML="";s.slice(0,6).forEach((a,i)=>{const e=document.createElement("button");e.className="mini mini-link";e.innerHTML=`<b>${esc((a.category||"OTHER").toUpperCase())}</b><h4>${esc(storyTitle(a))}</h4><small>${String(i+2).padStart(2,"0")}</small>`;e.onclick=()=>{state.readerPage=i+1;renderReader();show("reader")};box.appendChild(e)});const old=$(".cover-image");if(old){const holder=document.createElement("div");holder.innerHTML=coverImage(cover,"cover-image","MAIN FEATURE");old.replaceWith(holder.firstElementChild)}}
function totalSpreads(){return 1+Math.max(1,state.selected.length)}
function layoutFor(index){const types=["feature","news","image-left","shorts","feature-dark","news","image-right"];return types[index%types.length]}
function linkButton(a){return a?.link?`<a class="source-link" href="${esc(a.link)}" target="_blank" rel="noopener">READ ORIGINAL ↗</a>`:""}
function hList(items,empty){return items?.length?`<ul>${items.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<p class="muted-copy">${esc(empty)}</p>`}
function renderReader(){sync();const stories=state.selected.length?state.selected:state.articles;if(!stories.length)return;const total=totalSpreads();state.readerPage=Math.max(0,Math.min(state.readerPage,total-1));const p=state.readerPage;$("#reader-page").textContent=`${String(p+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;$("#reader-status").textContent=`SPREAD ${String(p+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;
if(p===0){const cover=stories[0];const st=storyFor(cover);const tags=articleTags(cover);$("#spread").innerHTML=`<section class="page cover-page">${coverImage(cover,"reader-cover-image","COVER STORY")}<div class="tag">WEEKLY · ${esc((cover?.category||"OTHER").toUpperCase())}</div><h2>${esc(storyTitle(cover))}</h2><p class="dek">${esc(st?.dek||cover?.description||"")}</p><div class="tag-row">${tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div><p class="cover-kicker"><strong>THE WEEKLY / ISSUE 036</strong></p></section><section class="page index-page"><div class="index-kicker">CONTENTS</div><h2>THIS ISSUE</h2><p class="index-intro">${stories.length} stories selected from ${state.articles.length} collected articles.</p><div class="toc">${stories.slice(0,10).map((a,i)=>`<button data-reader-index="${i+1}"><span>${String(i+1).padStart(2,"0")}</span><strong>${esc(storyTitle(a))}</strong><em>${esc((a.category||"OTHER").toUpperCase())}</em></button>`).join("")}</div>${stories.length>10?`<p class="muted-copy">+ ${stories.length-10} more stories in the full issue.</p>`:""}</section>`;
$("#spread").querySelectorAll("[data-reader-index]").forEach(b=>b.onclick=()=>{state.readerPage=Number(b.dataset.readerIndex);renderReader()});return}
const a=stories[p-1];const st=storyFor(a)||{};const h=a.headings||{};const h1=(h.h1||[]).filter(Boolean);const h2=(h.h2||[]).filter(Boolean);const desc=a.description||"";const type=layoutFor(p-1);const tags=articleTags(a);const sourceLabel=esc(a.source||"ORIGINAL SOURCE");const pageDate=esc((a.published||"").slice(0,10));const image=coverImage(a,"reader-story-image","ORIGINAL IMAGE");
if(type==="feature"||type==="feature-dark"){ $("#spread").innerHTML=`<section class="page article-page layout-feature ${type}">${image}<div class="story-running"><span>${sourceLabel}</span><span>${pageDate}</span></div><div class="tag">${esc((a.category||"OTHER").toUpperCase())}</div><h2>${esc(storyTitle(a))}</h2><p class="dek">${esc(desc||st.dek||h1[0]||"")}</p><div class="feature-number">${String(p).padStart(2,"0")}</div></section><section class="page article-page editorial-page"><div class="story-head"><span>THE STORY</span><h3>${esc(h1[0]||storyTitle(a))}</h3></div><div class="columns"><div><p>${esc(desc||"The original feed did not provide a longer description.")}</p>${h1[1]?`<p class="source-heading secondary">${esc(h1[1])}</p>`:""}</div><div><h3>HEADLINES</h3>${hList(h2,"No H2 headings were exposed by the source page.")}</div></div><div class="tag-row">${tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div>${linkButton(a)}</section>`;return}
if(type==="image-left"||type==="image-right"){const spacer="<div class=\"image-spacer\"></div>";const first=type==="image-left"?image:spacer;const second=type==="image-right"?image:spacer;$("#spread").innerHTML=`<section class="page article-page image-page"><div class="story-running"><span>${sourceLabel}</span><span>${pageDate}</span></div>${first}<div class="tag">${esc((a.category||"OTHER").toUpperCase())}</div><h2>${esc(storyTitle(a))}</h2><p class="dek">${esc(desc||st.dek||"")}</p>${linkButton(a)}</section><section class="page article-page image-page"><div class="story-running"><span>WEEKLY</span><span>${String(p).padStart(2,"0")}</span></div>${second}<div class="story"><h3>ORIGINAL STRUCTURE</h3>${hList([...h1,...h2],"This source did not expose article headings.")}</div><div class="story"><h3>FROM THE SOURCE</h3><p>${esc(desc||"Read the original article for the complete story.")}</p></div></section>`;return}
if(type==="shorts"){const related=stories.slice(Math.max(0,p-3),p+2).filter(x=>x!==a).slice(0,4);$("#spread").innerHTML=`<section class="page article-page shorts-page"><div class="story-running"><span>${sourceLabel}</span><span>${pageDate}</span></div>${image}<div class="tag">${esc((a.category||"OTHER").toUpperCase())} · SHORT READ</div><h2>${esc(storyTitle(a))}</h2><p class="dek">${esc(desc||st.dek||"")}</p>${linkButton(a)}</section><section class="page shorts-index"><div class="index-kicker">QUICK READS</div><h2>MORE FROM THIS ISSUE</h2>${related.map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><div><b>${esc((x.category||"OTHER").toUpperCase())}</b><h3>${esc(storyTitle(x))}</h3><small>${esc(x.source||"")}</small></div></article>`).join("")}<div class="story source-box"><h3>SOURCE NOTES</h3><p>${esc(desc||"The full article lives at the original publication.")}</p>${linkButton(a)}</div></section>`;return}
$("#spread").innerHTML=`<section class="page article-page news-page"><div class="story-running"><span>${sourceLabel}</span><span>${pageDate}</span></div><div class="tag">${esc((a.category||"OTHER").toUpperCase())} · ${esc(a.source||"")}</div><h2>${esc(storyTitle(a))}</h2><p class="dek">${esc(desc||st.dek||"")}</p>${image}<div class="story"><h3>HEADLINE STRUCTURE</h3><p class="source-heading">${esc(h1[0]||a.title)}</p>${h1[1]?`<p class="source-heading secondary">${esc(h1[1])}</p>`:""}</div></section><section class="page article-page editorial-page"><div class="story-head"><span>ARTICLE MAP</span><h3>WHAT THE SOURCE SAYS</h3></div>${hList(h2,"No H2 headings were exposed by the source page.")}<div class="story"><h3>DESCRIPTION</h3><p>${esc(desc||"Read the original article for the full story.")}</p></div><div class="tag-row">${tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div>${linkButton(a)}</section>`}
async function loadArticles(){try{const[a,e]=await Promise.all([fetch("data/articles.json?ts="+Date.now()),fetch("data/editorial.json?ts="+Date.now())]);const ad=await a.json();state.articles=ad.articles||[];state.editorial=e.ok?await e.json():null}catch(err){console.warn(err)}state.selected=[];state.articles.forEach(a=>{if(!Array.isArray(a.tags)||!a.tags.length)a.tags=deriveTags(a)});try{const saved=JSON.parse(localStorage.getItem("weekly.selectedTags")||"[]");state.selectedTags=new Set(saved.map(x=>String(x).toUpperCase()))}catch(e){}
try{const savedCustom=JSON.parse(localStorage.getItem("weekly.customTags")||"[]");state.customTags=new Set(savedCustom.map(x=>String(x).toUpperCase()))}catch(e){}}
function updateDash(){$("#source-stat").textContent=`${state.sources.filter(s=>s.enabled!==false).length} SOURCES`;$(`#found-stat`).textContent=`${state.articles.length} STORIES`;$(`#selected-stat`).textContent=`${state.selected.length} SELECTED`}
async function load(){await Promise.all([loadArticles(),refreshSources()]);renderAll()}
function renderAll(){renderSources();renderTags();renderArticles();renderMagazine();renderReader();updateDash()}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));const topicInput=$("#custom-topic-input");const addTopicBtn=$("#add-custom-topic");if(addTopicBtn&&topicInput){const submitTopic=()=>{if(addCustomTopic(topicInput.value))topicInput.value=""};addTopicBtn.onclick=submitTopic;topicInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();submitTopic()}})}document.querySelectorAll("[data-topic]").forEach(b=>b.onclick=()=>addCustomTopic(b.dataset.topic));$("#generate").onclick=()=>{state.selected=chooseRandomStories(candidatePool());state.shuffled=false;renderArticles();renderMagazine();show("magazine")};$("#reshuffle").onclick=()=>{state.selected=chooseRandomStories(candidatePool());state.shuffled=false;renderArticles();renderMagazine()};$("#back-to-articles").onclick=()=>show("articles");$("#open-reader").onclick=()=>{state.readerPage=0;renderReader();show("reader")};$("#close-reader").onclick=()=>show("magazine");$("#prev-page").onclick=()=>{state.readerPage=(state.readerPage-1+totalSpreads())%totalSpreads();renderReader()};$("#next-page").onclick=()=>{state.readerPage=(state.readerPage+1)%totalSpreads();renderReader()};$("#add-source").onclick=addSource;$("#refresh-sources").onclick=refreshSources;document.addEventListener("keydown",e=>{if(!$("#reader").classList.contains("active"))return;if(e.key==="ArrowLeft")$("#prev-page").click();if(e.key==="ArrowRight")$("#next-page").click()});const d=new Date();$("#today").textContent=d.toLocaleDateString("es-CL",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase();$("#issue-date").textContent=$("#today").textContent;load();
