const state={sources:[],articles:[],selected:[],selectedTags:new Set(),editorial:null,readerPage:0,tagPool:[],shuffled:false};
const titles={dashboard:"Dashboard",sources:"My Sources",articles:"This Week",magazine:"Magazine",reader:"Reader",archive:"Archive"};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const cfg=window.WEEKLY_CONFIG||{};
const hasSupabase=()=>Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes("YOUR_PROJECT_REF")&&!cfg.supabaseAnonKey.includes("YOUR_SUPABASE"));
const apiBase=()=>cfg.supabaseUrl.replace(/\/$/,"")+"/rest/v1";
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));$("#screen-title").textContent=titles[id]||"Dashboard"}
function setConnection(text,ok=false){const el=$("#connection-status");if(!el)return;el.textContent=text;el.classList.toggle("ok",ok)}
async function db(path,options={}){const headers={apikey:cfg.supabaseAnonKey,...(options.headers||{})};const r=await fetch(apiBase()+path,{...options,headers});if(!r.ok){let msg=await r.text();throw new Error(`${r.status} ${msg}`)}if(r.status===204)return null;return r.json()}
async function loadSources(){if(!hasSupabase())throw new Error("Supabase no está configurado. Crea config.js.");return db("/sources?select=id,name,url,category,enabled,created_at&order=created_at.asc")}
async function addSource(){if(!hasSupabase()){alert("Primero configura Supabase en config.js. Mira README.md.");return}const name=prompt("Nombre del medio:","");if(name===null)return;const url=prompt("URL del RSS / Atom:","");if(url===null)return;const category=prompt("Categoría (Technology, Games, Culture, World, Other):","Technology");if(category===null)return;if(!name.trim()||!url.trim()){alert("El nombre y la URL son obligatorios.");return}try{await db("/sources",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({name:name.trim(),url:url.trim(),category:category.trim()||"Other",enabled:true})});await refreshSources();show("sources");alert("Feed añadido correctamente. 🎉")}catch(err){console.error(err);alert("No pude guardar el feed.\n\n"+err.message)}}
async function removeSource(id,name){if(!confirm(`¿Eliminar "${name}" de WEEKLY?`))return;try{await db(`/sources?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});await refreshSources()}catch(err){console.error(err);alert("No pude eliminar el feed.\n\n"+err.message)}}
function renderSources(){const box=$("#source-grid");box.innerHTML="";state.sources.forEach(s=>{const e=document.createElement("div");e.className="source";e.innerHTML='<span class="dot"></span><div class="source-copy"><strong></strong><small></small><em></em></div><button class="remove">REMOVE</button>';e.querySelector("strong").textContent=s.name;e.querySelector("small").textContent=`${s.category||"Other"} · RSS`;e.querySelector("em").textContent=s.url;e.querySelector(".remove").onclick=()=>removeSource(s.id,s.name);box.appendChild(e)});$("#source-count").textContent=`${state.sources.filter(s=>s.enabled!==false).length} ACTIVE FEEDS`}
async function refreshSources(){if(!hasSupabase()){setConnection("SUPABASE NOT CONFIGURED");renderSources();return}try{state.sources=await loadSources();setConnection("SUPABASE CONNECTED",true);renderSources();updateDash()}catch(err){console.error(err);setConnection("SUPABASE ERROR");alert("No pude leer Supabase.\n\n"+err.message)}}
const TAG_STOP=new Set("the a an and or of to in on for with from by is are was were this that how why what your you new news more into about after as at it its there their they has have had will would could should just than then very been being not you our their from about today week best one two three get gets can may might while over under who where when into onto only also says said according latest plus here this these those all any any more most some such other another much many much new own its his her them he she we us i me my mine de an der die das und für mit von ist sind auf den im die der ein eine the los las del para por con que una uno como sus más este esta estos estas puede pueden fue han ha hay ya hoy según sobre entre tras al se su es en de".split());
function deriveTags(a){
  const text=`${a.title||""} ${a.description||""} ${(a.headings?.h1||[]).join(" ")} ${(a.headings?.h2||[]).join(" ")}`.toLowerCase();
  const words=(text.match(/[a-zA-ZÀ-ÿ0-9]{4,}/g)||[]).map(w=>w.toLowerCase()).filter(w=>!TAG_STOP.has(w));
  const freq={}; words.forEach(w=>freq[w]=(freq[w]||0)+1);
  const generic=new Set(["history","story","article","selected","source","week","today","best","world","thing","things","edition","review","technology","games"]);
  const keywords=Object.entries(freq).filter(([w])=>!generic.has(w)).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,5).map(([w])=>w.toUpperCase());
  const base=[];
  if(a.category)base.push(String(a.category).toUpperCase());
  if(Array.isArray(a.tags))base.push(...a.tags.map(x=>String(x).toUpperCase()));
  return [...new Set([...base,...keywords])].slice(0,8);
}
function allTags(){const m=new Map();state.articles.forEach(a=>{(a.tags?.length?a.tags:deriveTags(a)).forEach(t=>m.set(t,(m.get(t)||0)+1))});return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
function matchesTags(a){if(!state.selectedTags.size)return true;const tags=a.tags?.length?a.tags:deriveTags(a);return tags.some(t=>state.selectedTags.has(String(t).toUpperCase()));}
function candidatePool(){return state.articles.filter(matchesTags);}
function shuffleArray(arr){const out=[...arr];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function chooseRandomStories(pool= candidatePool()){
  const ranked=shuffleArray(pool.slice()).sort((a,b)=>((b.editorialScore||0)-(a.editorialScore||0))*(Math.random()*.55+.45));
  const out=[],counts={};
  for(const a of ranked){const cat=a.category||"Other";if((counts[cat]||0)>=8)continue;out.push(a);counts[cat]=(counts[cat]||0)+1;if(out.length>=24)break}
  return out;
}
function sync(){
  if(!state.selected.length || state.shuffled){
    state.selected=chooseRandomStories();
    state.shuffled=false;
  }
  if(!state.selected.length) state.selected=state.articles.filter(a=>a.selected).slice(0,24);
  updateCounts();
}
function renderTags(){
  const box=$("#tag-cloud");if(!box)return;box.innerHTML="";
  const tags=allTags();
  $("#tag-count").textContent=`${state.selectedTags.size} SELECTED`;
  tags.forEach(([tag,count])=>{const b=document.createElement("button");b.className="tag-chip"+(state.selectedTags.has(tag)?" active":"");b.innerHTML=`<span>${esc(tag)}</span><small>${count}</small>`;b.onclick=()=>{if(state.selectedTags.has(tag))state.selectedTags.delete(tag);else state.selectedTags.add(tag);localStorage.setItem("weekly.selectedTags",JSON.stringify([...state.selectedTags]));state.selected=[];state.shuffled=true;renderTags();renderArticles();renderMagazine();};box.appendChild(b)});
}
function renderArticles(){
  const box=$("#article-list");if(!box)return;const pool=candidatePool();
  if(!state.selected.length || state.shuffled){ state.selected=chooseRandomStories(pool); state.shuffled=false; }
  $("#pool-stat").textContent=`${pool.length} STORIES IN POOL`;
  $("#pool-note").textContent=state.selectedTags.size?`Tags: ${[...state.selectedTags].join(" · ")}`:"Todo el feed está disponible. WEEKLY elegirá una combinación al azar.";
  box.innerHTML="";
  shuffleArray(pool).slice(0,12).forEach(a=>{const l=document.createElement("div");l.className="article preview-article";const tags=(a.tags?.length?a.tags:deriveTags(a)).slice(0,4);l.innerHTML=`<div class="article-thumb">${a.image?`<img src="${esc(a.image)}" alt="">`:""}</div><div><span class="cat">${esc((a.category||"OTHER").toUpperCase())}</span><h3>${esc(a.title)}</h3><p>${esc(a.source)} · ${esc((a.published||"").slice(0,10))}</p><div class="mini-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div></div><span class="score">${a.editorialScore||"-"}</span>`;box.appendChild(l)});
  updateCounts();
}
function updateCounts(){const pool=candidatePool();$("#article-count").textContent=`${state.selected.length} SELECTED · ${pool.length} IN POOL`;$("#selected-stat").textContent=`${state.selected.length} SELECTED`}
function updateDash(){$("#source-stat").textContent=`${state.sources.length} SOURCES`;$("#found-stat").textContent=`${state.articles.length} STORIES`;$("#selected-stat").textContent=`${state.selected.length} SELECTED`}
function storyFor(a){return (state.editorial?.stories||[]).find(s=>s.article_id===state.articles.indexOf(a))||null}
function coverImage(a,cls="cover-image"){return a?.image?`<div class="${cls}"><img src="${esc(a.image)}" alt=""><span>WEEKLY FEATURE</span></div>`:`<div class="${cls}"><span>WEEKLY FEATURE</span></div>`}
function renderMagazine(){sync();const s=state.selected;const cover=s[0];const cs=cover?storyFor(cover):null;$("#cover-dek").textContent=`${s.length} stories · ${state.sources.length} sources · ${state.editorial?.status==="ai"?"AI EDITOR":"RSS EDITOR"}`;$("#mag-cover-title").textContent=cs?.headline||cover?.title||"THE NEWS DESERVES A BETTER INTERFACE.";$("#issue-number").textContent="036";const box=$("#cover-stories");box.innerHTML="";(s.length?s:s.slice(0,6)).slice(0,5).forEach(a=>{const st=storyFor(a);const e=document.createElement("div");e.className="mini";e.innerHTML=`<b>${esc((a.category||"OTHER").toUpperCase())}</b><h4>${esc(st?.headline||a.title)}</h4>`;box.appendChild(e)});const image=coverImage(cover);const old=$(".cover-image");if(old){const holder=document.createElement("div");holder.innerHTML=image;old.replaceWith(holder.firstElementChild)}}
function totalSpreads(){return 1+Math.max(1,state.selected.length)}
function renderReader(){sync();const stories=state.selected.length?state.selected:state.articles;if(!stories.length)return;const total=totalSpreads();state.readerPage=Math.max(0,Math.min(state.readerPage,total-1));const p=state.readerPage;$("#reader-page").textContent=`${String(p+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;$("#reader-status").textContent=`SPREAD ${String(p+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;
if(p===0){const cover=state.editorial?.cover_story!=null?state.articles[state.editorial.cover_story]:stories[0];const st=cover?storyFor(cover):null;$("#spread").innerHTML=`<section class="page cover-page">${coverImage(cover,"reader-cover-image")}<div class="tag">WEEKLY · ${esc((cover?.category||"OTHER").toUpperCase())}</div><h2>${esc(st?.headline||cover?.title||"WEEKLY")}</h2><p class="dek">${esc(st?.dek||cover?.description||"")}</p><p><strong>THE COVER STORY</strong></p></section><section class="page"><div class="story"><h3>EDITOR'S NOTE</h3><p>${esc(state.editorial?.editor_note||"Una selección editorial automática.")}</p></div><div class="story"><h3>THIS ISSUE</h3><p>${stories.length} historias seleccionadas de ${state.articles.length} artículos encontrados en ${state.sources.length} fuentes.</p></div><div class="story"><h3>SECTIONS</h3><p>${esc((state.editorial?.sections||[]).map(x=>x.name).join(" · ")||"WEEKLY PICKS")}</p></div></section>`;return}
const a=stories[p-1];const st=storyFor(a)||{};const heads=st.headings||a.headings||{};const h1=(heads.h1||[]).filter(Boolean);const h2=(heads.h2||[]).filter(Boolean);const keyPoints=(h2.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join(""));const desc=a.description||st.dek||"";$("#spread").innerHTML=`<section class="page article-page">${coverImage(a,"reader-story-image")}<div class="tag">${esc((a.category||"OTHER").toUpperCase())} · ${esc(a.source||"")}</div><h2>${esc(st.headline||a.title)}</h2><p class="dek">${esc(desc)}</p><div class="story-body"><h3>H1 / ORIGINAL HEADLINE</h3><p class="source-heading">${esc(h1[0]||a.title)}</p>${h1[1]?`<p class="source-heading secondary">${esc(h1[1])}</p>`:""}</div></section><section class="page article-page"><div class="story"><h3>H2 / ARTICLE HEADINGS</h3>${keyPoints?`<ul>${keyPoints}</ul>`:`<p>No H2 headings were exposed by the source page.</p>`}</div><div class="story"><h3>FROM THE SOURCE</h3><p>${esc(desc||"Read the original article for the full story.")}</p></div><div class="story source-box"><h3>SOURCE</h3><p>${esc(a.source||"")}</p><a href="${esc(a.link||"#")}" target="_blank" rel="noopener">READ ORIGINAL ↗</a></div></section>`}
async function loadArticles(){try{const [a,e]=await Promise.all([fetch("data/articles.json?ts="+Date.now()),fetch("data/editorial.json?ts="+Date.now())]);const ad=await a.json();state.articles=ad.articles||[];state.editorial=e.ok?await e.json():null}catch(err){console.warn(err)}state.selected=[];state.articles.forEach(a=>{if(!Array.isArray(a.tags)||!a.tags.length)a.tags=deriveTags(a)});try{const saved=JSON.parse(localStorage.getItem("weekly.selectedTags")||"[]");state.selectedTags=new Set(saved.map(x=>String(x).toUpperCase()))}catch(e){}}
async function load(){await Promise.all([loadArticles(),refreshSources()]);renderAll()}
function renderAll(){renderSources();renderTags();renderArticles();renderMagazine();renderReader();updateDash()}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));$("#generate").onclick=()=>{state.selected=chooseRandomStories();state.shuffled=false;renderArticles();renderMagazine();show("magazine")};$("#reshuffle").onclick=()=>{state.selected=chooseRandomStories();state.shuffled=false;renderArticles();renderMagazine()};$("#back-to-articles").onclick=()=>show("articles");$("#open-reader").onclick=()=>{state.readerPage=0;renderReader();show("reader")};$("#close-reader").onclick=()=>show("magazine");$("#prev-page").onclick=()=>{state.readerPage=(state.readerPage-1+totalSpreads())%totalSpreads();renderReader()};$("#next-page").onclick=()=>{state.readerPage=(state.readerPage+1)%totalSpreads();renderReader()};$("#add-source").onclick=addSource;$("#refresh-sources").onclick=refreshSources;document.addEventListener("keydown",e=>{if(!$("#reader").classList.contains("active"))return;if(e.key==="ArrowLeft")$("#prev-page").click();if(e.key==="ArrowRight")$("#next-page").click()});const d=new Date();$("#today").textContent=d.toLocaleDateString("es-CL",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase();$("#issue-date").textContent=$("#today").textContent;load();
