from pathlib import Path
p=Path('/mnt/data/v095/app.js')
s=p.read_text()
s=s.replace('const state={sources:[],articles:[],selected:[],selectedTags:new Set(),customTags:new Set(),editorial:null,readerPage:0,shuffled:false};', 'const state={sources:[],articles:[],selected:[],selectedTags:new Set(),customTags:new Set(),editorial:null,readerPage:0,readerView:"single",shuffled:false};')
old='''function totalSpreads(){const {pages}=buildReaderPages();return Math.max(1,Math.ceil(pages.length/2))}\nfunction linkButton(a){return a?.link?`<a class="source-link" href="${esc(a.link)}" target="_blank" rel="noopener">READ ORIGINAL ↗</a>`:""}\nfunction renderReader(){\n  sync(); const model=buildReaderPages(); const pages=model.pages; if(!pages.length)return;\n  const total=Math.ceil(pages.length/2); state.readerPage=Math.max(0,Math.min(state.readerPage,total-1)); const spreadStart=state.readerPage*2;\n  $("#reader-page").textContent=`${String(spreadStart+1).padStart(2,"0")}–${String(Math.min(spreadStart+2,pages.length)).padStart(2,"0")} / ${String(pages.length).padStart(2,"0")}`;\n  $("#reader-status").textContent=`SPREAD ${String(state.readerPage+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;\n  const right=pages[spreadStart+1]||`<section class="page blank-page"><span>WEEKLY</span></section>`;\n  $("#spread").innerHTML=`${pages[spreadStart]}${right}`;\n  $("#spread").querySelectorAll("[data-reader-target]").forEach(b=>b.onclick=()=>{const idx=Number(b.dataset.readerTarget);state.readerPage=Math.floor(model.articleStarts[idx]/2);renderReader()});\n}\n'''
new='''function totalReaderPages(){const {pages}=buildReaderPages();return Math.max(1,pages.length)}\nfunction totalSpreads(){return Math.max(1,Math.ceil(totalReaderPages()/2))}\nfunction linkButton(a){return a?.link?`<a class="source-link" href="${esc(a.link)}" target="_blank" rel="noopener">READ ORIGINAL ↗</a>`:""}\nfunction renderReader(){\n  sync(); const model=buildReaderPages(); const pages=model.pages; if(!pages.length)return;\n  const total=pages.length;\n  state.readerPage=Math.max(0,Math.min(state.readerPage,total-1));\n  const spread=document.querySelector("#spread");\n  if(state.readerView==="spread") {\n    const spreadStart=Math.floor(state.readerPage/2)*2;\n    state.readerPage=spreadStart;\n    $("#reader-page").textContent=`${String(spreadStart+1).padStart(2,"0")}–${String(Math.min(spreadStart+2,total)).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;\n    $("#reader-status").textContent=`SPREAD ${String(Math.floor(spreadStart/2)+1).padStart(2,"0")} / ${String(Math.ceil(total/2)).padStart(2,"0")}`;\n    const right=pages[spreadStart+1]||`<section class="page blank-page"><span>WEEKLY</span></section>`;\n    spread.classList.remove("single-view"); spread.classList.add("spread-view");\n    spread.innerHTML=`${pages[spreadStart]}${right}`;\n  } else {\n    $("#reader-page").textContent=`${String(state.readerPage+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;\n    $("#reader-status").textContent=`PAGE ${String(state.readerPage+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;\n    spread.classList.remove("spread-view"); spread.classList.add("single-view");\n    spread.innerHTML=pages[state.readerPage];\n  }\n  $("#spread").querySelectorAll("[data-reader-target]").forEach(b=>b.onclick=()=>{const idx=Number(b.dataset.readerTarget);const target=model.articleStarts[idx]??0;state.readerPage=state.readerView==="spread"?Math.floor(target/2)*2:target;renderReader()});\n  updateReaderViewButtons();\n}\nfunction updateReaderViewButtons(){\n  document.querySelectorAll("[data-reader-view]").forEach(b=>b.classList.toggle("active",b.dataset.readerView===state.readerView));\n}\nfunction setReaderView(view){\n  state.readerView=view==="spread"?"spread":"single";\n  if(state.readerView==="spread")state.readerPage=Math.floor(state.readerPage/2)*2;\n  renderReader();\n}\n'''
if old not in s: raise SystemExit('old reader block not found')
s=s.replace(old,new)
s=s.replace('e.onclick=()=>{state.readerPage=i+1;renderReader();show("reader")};', 'e.onclick=()=>{const model=buildReaderPages();state.readerPage=state.readerView==="spread"?Math.floor((model.articleStarts[i]||0)/2)*2:(model.articleStarts[i]||0);renderReader();show("reader")};')
s=s.replace('document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.screen));', 'document.querySelectorAll("[data-reader-view]").forEach(b=>b.onclick=()=>setReaderView(b.dataset.readerView));document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.screen));')
s=s.replace('$("#prev-page").onclick=()=>{state.readerPage=(state.readerPage-1+totalSpreads())%totalSpreads();renderReader()};$("#next-page").onclick=()=>{state.readerPage=(state.readerPage+1)%totalSpreads();renderReader()};', '$("#prev-page").onclick=()=>{const total=totalReaderPages();const step=state.readerView==="spread"?2:1;state.readerPage=(state.readerPage-step+total)%total;if(state.readerView==="spread")state.readerPage=Math.floor(state.readerPage/2)*2;renderReader()};$("#next-page").onclick=()=>{const total=totalReaderPages();const step=state.readerView==="spread"?2:1;state.readerPage=(state.readerPage+step)%total;if(state.readerView==="spread")state.readerPage=Math.floor(state.readerPage/2)*2;renderReader()};')
s=s.replace('if(e.key==="ArrowLeft")$("#prev-page").click();if(e.key==="ArrowRight")$("#next-page").click()', 'if(e.key==="ArrowLeft")$("#prev-page").click();if(e.key==="ArrowRight")$("#next-page").click()')
p.write_text(s)
